**Name: Solanki Ravi**
    
**Course: Data Science**
    
**Sem: 7**
    
**Subject: Image Processing**

1. Implement functions for encoding and decoding an image using the following methods:

    A. Transform Coding (using DCT for forward transform)
    
    B. Huffman Encoding
    
    C. LZWEncoding
    
    D. Run-Length Encoding
    
    E. Arithmetic Coding

For each method, display the Compression Ratio and calculate the Root Mean Square Error (RMSE) between the original and reconstructed image to quantify any loss of information

In [12]:
import numpy as np
import cv2
from scipy.fftpack import dct, idct
import heapq
import collections
from sklearn.metrics import mean_squared_error
import math

In [13]:
# Helper function for RMSE calculation
def calculate_rmse(original, reconstructed):
    return np.sqrt(mean_squared_error(original.flatten(), reconstructed.flatten()))

# Helper function for compression ratio
def calculate_compression_ratio(original_size, compressed_size):
    return original_size / compressed_size


# A. Transform Coding (DCT Based)

In [14]:
# DCT encoding
def dct_encode(image, block_size=8):
    h, w = image.shape
    dct_blocks = np.zeros((h, w), dtype=np.float32)
    for i in range(0, h, block_size):
        for j in range(0, w, block_size):
            block = image[i:i+block_size, j:j+block_size]
            dct_blocks[i:i+block_size, j:j+block_size] = dct(dct(block, axis=0, norm='ortho'), axis=1, norm='ortho')
    return dct_blocks

# DCT decoding
def dct_decode(dct_blocks, block_size=8):
    h, w = dct_blocks.shape
    reconstructed = np.zeros((h, w), dtype=np.float32)
    for i in range(0, h, block_size):
        for j in range(0, w, block_size):
            block = dct_blocks[i:i+block_size, j:j+block_size]
            reconstructed[i:i+block_size, j:j+block_size] = idct(idct(block, axis=0, norm='ortho'), axis=1, norm='ortho')
    return np.clip(reconstructed, 0, 255).astype(np.uint8)


In [23]:
# Example 8x8 grayscale image (pixel values between 0-255)
original_image = np.array([
    [50, 55, 61, 66, 70, 61, 64, 73],
    [67, 55, 66, 90, 109, 85, 69, 52],
    [25, 59, 68, 113, 184, 104, 46, 73],
    [63, 59, 71, 122, 144, 126, 50, 69],
    [67, 61, 68, 104, 146, 88, 68, 70],
    [79, 67, 60, 90, 57, 68, 58, 75],
    [85, 78, 84, 59, 55, 61, 65, 83],
    [87, 49, 49, 68, 65, 76, 78, 94]
], dtype=np.uint8)

# Perform DCT encoding
dct_encoded = dct_encode(original_image)
    
# Perform DCT decoding to reconstruct the image
dct_decoded = dct_decode(dct_encoded)

# Calculate Compression Ratio and RMSE
original_size = original_image.size * original_image.itemsize
compressed_size = dct_encoded.size * dct_encoded.itemsize  # Can adjust based on quantization for real compression
compression_ratio = calculate_compression_ratio(original_size, compressed_size)
rmse = calculate_rmse(original_image, dct_decoded)

print("Original Image:\n", original_image)
print("DCT Encoded (Frequency Domain):\n", dct_encoded)
print("Reconstructed Image:\n", dct_decoded)
print(f"Compression Ratio: {compression_ratio:.2f}")
print(f"RMSE: {rmse:.2f}")

Original Image:
 [[ 50  55  61  66  70  61  64  73]
 [ 67  55  66  90 109  85  69  52]
 [ 25  59  68 113 184 104  46  73]
 [ 63  59  71 122 144 126  50  69]
 [ 67  61  68 104 146  88  68  70]
 [ 79  67  60  90  57  68  58  75]
 [ 85  78  84  59  55  61  65  83]
 [ 87  49  49  68  65  76  78  94]]
DCT Encoded (Frequency Domain):
 [[ 6.0387500e+02 -3.1663446e+01 -8.4772408e+01  2.7025295e+01
   5.9625000e+01 -2.6122663e+01  6.0245891e+00 -1.2159461e+00]
 [ 4.6301618e+00 -1.6079477e+01 -7.3930679e+01  1.1386600e+01
   6.1034756e+00 -2.3492607e+01 -1.0829472e+01  1.1151272e+01]
 [-5.4891235e+01  3.4339614e+00  8.6425331e+01 -2.1633005e+01
  -2.7345310e+01  2.8754131e+01  3.0528545e+00  3.1543176e+00]
 [-3.4095802e+01  2.6057545e+01  5.3000034e+01 -2.4241652e+01
  -1.9311680e+01  2.5285940e+01 -4.3974919e+00 -5.3044448e+00]
 [ 6.6250000e+00 -1.6961658e+01 -1.7011949e-01  1.2130071e+01
   8.8750000e+00  4.8020830e+00  3.1823435e+00 -1.8482486e+00]
 [-1.6967047e+00  6.0731049e+00  5.2455964e+

# B. Huffman Encoding

In [24]:
# Huffman encoding and decoding functions
class HuffmanNode:
    def __init__(self, symbol, frequency):
        self.symbol = symbol
        self.frequency = frequency
        self.left = None
        self.right = None

    def __lt__(self, other):
        return self.frequency < other.frequency

def build_huffman_tree(frequency_dict):
    heap = [HuffmanNode(symbol, freq) for symbol, freq in frequency_dict.items()]
    heapq.heapify(heap)
    while len(heap) > 1:
        left = heapq.heappop(heap)
        right = heapq.heappop(heap)
        merged = HuffmanNode(None, left.frequency + right.frequency)
        merged.left = left
        merged.right = right
        heapq.heappush(heap, merged)
    return heap[0]

def build_huffman_codes(node, prefix="", code_dict={}):
    if node.symbol is not None:
        code_dict[node.symbol] = prefix
    else:
        build_huffman_codes(node.left, prefix + "0", code_dict)
        build_huffman_codes(node.right, prefix + "1", code_dict)
    return code_dict

def huffman_encode(image):
    frequency_dict = collections.Counter(image.flatten())
    huffman_tree = build_huffman_tree(frequency_dict)
    huffman_codes = build_huffman_codes(huffman_tree)
    encoded_image = ''.join(huffman_codes[pixel] for pixel in image.flatten())
    return encoded_image, huffman_codes

# Function to decode Huffman encoded image
def huffman_decode(encoded_image, huffman_codes, shape):
    reverse_codes = {v: k for k, v in huffman_codes.items()}
    current_code = ""
    decoded_pixels = []
    
    for bit in encoded_image:
        current_code += bit
        if current_code in reverse_codes:
            decoded_pixels.append(reverse_codes[current_code])
            current_code = ""
    
    return np.array(decoded_pixels).reshape(shape)


In [25]:
# Example 4x4 image for simplicity
example_image = np.array([
    [45, 45, 255, 255],
    [45, 45, 255, 255],
    [45, 200, 200, 255],
    [45, 200, 200, 255]
], dtype=np.uint8)

# Huffman Encode the image
encoded_image, huffman_codes = huffman_encode(example_image)

# Decode the encoded image
decoded_image = huffman_decode(encoded_image, huffman_codes, example_image.shape)

# Calculate Compression Ratio
original_size = example_image.size * 8  # 8 bits per pixel in original image
compressed_size = len(encoded_image)
compression_ratio = original_size / compressed_size

# Display results
print("Original Image:\n", example_image)
print("Huffman Codes:", huffman_codes)
print("Encoded Image:", encoded_image)
print("Decoded Image:\n", decoded_image)
print(f"Compression Ratio: {compression_ratio:.2f}")

Original Image:
 [[ 45  45 255 255]
 [ 45  45 255 255]
 [ 45 200 200 255]
 [ 45 200 200 255]]
Huffman Codes: {45: '0', 200: '10', 255: '11'}
Encoded Image: 00111100111101010110101011
Decoded Image:
 [[ 45  45 255 255]
 [ 45  45 255 255]
 [ 45 200 200 255]
 [ 45 200 200 255]]
Compression Ratio: 4.92


# C. LZW Encoding

In [26]:
# LZW encoding function
def lzw_encode(image):
    image = image.flatten()
    dictionary = {bytes([i]): i for i in range(256)}
    current_sequence = bytes([image[0]])
    encoded_data = []
    code = 256
    for pixel in image[1:]:
        sequence_plus_pixel = current_sequence + bytes([pixel])
        if sequence_plus_pixel in dictionary:
            current_sequence = sequence_plus_pixel
        else:
            encoded_data.append(dictionary[current_sequence])
            dictionary[sequence_plus_pixel] = code
            code += 1
            current_sequence = bytes([pixel])
    encoded_data.append(dictionary[current_sequence])
    return encoded_data

# Function to perform LZW Decoding
def lzw_decode(encoded_data):
    # Initialize the dictionary for decoding
    dictionary = {i: bytes([i]) for i in range(256)}
    code = 256  # Start codes for sequences longer than one byte
    
    # Decode the first value
    current_sequence = dictionary[encoded_data[0]]
    decoded_image = [current_sequence]
    
    for code_value in encoded_data[1:]:
        if code_value in dictionary:
            entry = dictionary[code_value]
        elif code_value == code:
            entry = current_sequence + current_sequence[:1]
        
        # Append decoded sequence
        decoded_image.append(entry)
        
        # Add new sequence to the dictionary
        dictionary[code] = current_sequence + entry[:1]
        code += 1
        current_sequence = entry
    
    # Convert to a 1D array of pixel values
    decoded_image = b''.join(decoded_image)
    return np.frombuffer(decoded_image, dtype=np.uint8)


In [27]:

# Example 4x4 grayscale image for simplicity
example_image = np.array([
    [45, 45, 45, 255],
    [45, 45, 255, 255],
    [200, 200, 45, 45],
    [200, 200, 255, 255]
], dtype=np.uint8)

# Step 1: LZW Encode the image
encoded_data = lzw_encode(example_image)

# Step 2: LZW Decode the encoded image
decoded_image = lzw_decode(encoded_data).reshape(example_image.shape)

# Calculate Compression Ratio
original_size = example_image.size * 8  # 8 bits per pixel in the original image
compressed_size = len(encoded_data) * 16  # Assuming each encoded entry takes 16 bits
compression_ratio = original_size / compressed_size

# Display results
print("Original Image:\n", example_image)
print("Encoded Data:", encoded_data)
print("Decoded Image:\n", decoded_image)
print(f"Compression Ratio: {compression_ratio:.2f}")


Original Image:
 [[ 45  45  45 255]
 [ 45  45 255 255]
 [200 200  45  45]
 [200 200 255 255]]
Encoded Data: [45, 256, 255, 257, 255, 200, 200, 256, 261, 255, 255]
Decoded Image:
 [[ 45  45  45 255]
 [ 45  45 255 255]
 [200 200  45  45]
 [200 200 255 255]]
Compression Ratio: 0.73


# D. Run-Length Encoding

In [28]:
import numpy as np

# Function to perform RLE Encoding
def rle_encode(image):
    # Flatten the image to treat it as a 1D sequence
    image = image.flatten()
    encoded_data = []
    i = 0

    # Traverse through the image pixels
    while i < len(image):
        count = 1
        while i + 1 < len(image) and image[i] == image[i + 1]:
            count += 1
            i += 1
        # Store the pixel value and its count
        encoded_data.append((image[i], count))
        i += 1
    return encoded_data

# Function to perform RLE Decoding
def rle_decode(encoded_data, shape):
    decoded_image = []

    # Expand each (value, count) pair
    for value, count in encoded_data:
        decoded_image.extend([value] * count)

    # Convert list to a numpy array and reshape to original image shape
    return np.array(decoded_image, dtype=np.uint8).reshape(shape)

# Example 4x4 grayscale image for simplicity
example_image = np.array([
    [45, 45, 45, 255],
    [45, 45, 255, 255],
    [200, 200, 45, 45],
    [200, 200, 255, 255]
], dtype=np.uint8)

# Step 1: RLE Encode the image
encoded_data = rle_encode(example_image)

# Step 2: RLE Decode the encoded image
decoded_image = rle_decode(encoded_data, example_image.shape)

# Calculate Compression Ratio
original_size = example_image.size * 8  # 8 bits per pixel in the original image
compressed_size = sum(len(bin(value)[2:]) + 8 for value, count in encoded_data)  # compressed size
compression_ratio = original_size / compressed_size

# Display results
print("Original Image:\n", example_image)
print("RLE Encoded Data:", encoded_data)
print("Decoded Image:\n", decoded_image)
print(f"Compression Ratio: {compression_ratio:.2f}")


Original Image:
 [[ 45  45  45 255]
 [ 45  45 255 255]
 [200 200  45  45]
 [200 200 255 255]]
RLE Encoded Data: [(45, 3), (255, 1), (45, 2), (255, 2), (200, 2), (45, 2), (200, 2), (255, 2)]
Decoded Image:
 [[ 45  45  45 255]
 [ 45  45 255 255]
 [200 200  45  45]
 [200 200 255 255]]
Compression Ratio: 1.05


# E. Arithmetic Coding 

In [29]:
from collections import Counter
import numpy as np

# Function to calculate probability ranges for each pixel value
def calculate_prob_ranges(sequence):
    total_pixels = len(sequence)
    freq = Counter(sequence)
    prob_ranges = {}
    current_low = 0.0

    # Calculate cumulative probability ranges for each pixel value
    for pixel_value, count in sorted(freq.items()):
        probability = count / total_pixels
        current_high = current_low + probability
        prob_ranges[pixel_value] = (current_low, current_high)
        current_low = current_high

    return prob_ranges

# Arithmetic encoding function
def arithmetic_encode(sequence, prob_ranges):
    low, high = 0.0, 1.0

    for pixel in sequence:
        pixel_low, pixel_high = prob_ranges[pixel]
        range_ = high - low
        high = low + range_ * pixel_high
        low = low + range_ * pixel_low

    return (low + high) / 2  # Encoded as a single value within the final range

# Arithmetic decoding function
def arithmetic_decode(encoded_value, prob_ranges, sequence_length):
    low, high = 0.0, 1.0
    decoded_sequence = []

    for _ in range(sequence_length):
        range_ = high - low
        for pixel, (pixel_low, pixel_high) in prob_ranges.items():
            pixel_range_low = low + range_ * pixel_low
            pixel_range_high = low + range_ * pixel_high
            if pixel_range_low <= encoded_value < pixel_range_high:
                decoded_sequence.append(pixel)
                low, high = pixel_range_low, pixel_range_high
                break

    return decoded_sequence

# Example image represented as a 4x4 grayscale image
example_image = np.array([
    [45, 45, 45, 255],
    [45, 45, 255, 255],
    [200, 200, 45, 45],
    [200, 200, 255, 255]
], dtype=np.uint8)

# Flatten the image to create a sequence
sequence = example_image.flatten()

# Step 1: Calculate probability ranges for each pixel value
prob_ranges = calculate_prob_ranges(sequence)

# Step 2: Encode the sequence using Arithmetic Encoding
encoded_value = arithmetic_encode(sequence, prob_ranges)

# Step 3: Decode the sequence to retrieve the original image
decoded_sequence = arithmetic_decode(encoded_value, prob_ranges, len(sequence))
decoded_image = np.array(decoded_sequence, dtype=np.uint8).reshape(example_image.shape)

# Calculate Compression Ratio
original_size = example_image.size * 8  # 8 bits per pixel in the original image
compressed_size = len(bin(int(encoded_value * (2 ** 32)))) - 2  # Approx. bits for encoding
compression_ratio = original_size / compressed_size

# Display results
print("Original Image:\n", example_image)
print("Encoded Value:", encoded_value)
print("Decoded Image:\n", decoded_image)
print(f"Compression Ratio: {compression_ratio:.2f}")


Original Image:
 [[ 45  45  45 255]
 [ 45  45 255 255]
 [200 200  45  45]
 [200 200 255 255]]
Encoded Value: 0.06236219020966758
Decoded Image:
 [[ 45  45  45 255]
 [ 45  45 255 255]
 [200 200  45  45]
 [200 200 255 255]]
Compression Ratio: 4.57
